### ISSUE TITLE
log view

### ISSUE THREAD

**Issue by PhilLAL** [luciozambon/eGiga2m#1]
Hi Lucio,
I would be interested by a log display for some values, and specifying a min and max Y value like `e-5` for 10^-5.
I tried clicking on log box but it doesn't seem to work: Y values stay linear
Is there anything to do to make it work?
Regards

**Comment by luciozambon** [comment]
Have you tried to use decimal notation i.e. 0.00001 ?

**Comment by PhilLAL** [comment]
when doing this, the wheel seems to indefinitely turn without displaying anything

**Comment by luciozambon** [comment]
this looks like a timeout problem
you can try to reduce the time interval and you could try to export to JSON format, that is the same content the client asks to the server in order to retrieve data

**Comment by PhilLAL** [comment]
JSON export works, but as soon as we enter a min or a max value, with log checked, no data is displayed.

**Comment by luciozambon** [comment]
I did some tests with vacuum pumps data, log scale and max and min set and it worked
I try to figure where may be the error
the max and min parameters are inserted in the data structur (chartConfig) passed to the chart library (HighCharts)

if (maxYArray[i-1]) chartConfig.yAxis[i-1].max = maxYArray[i-1];

probably the problem is a 0 that in log scale become minus infinity
Do you get different results moving the time range so thin that only 2 or 3 samples are left?
Can you change slightly the max and min value?
You could try a newer version of highcharts

**Comment by PhilLAL** [comment]
I checked with a serie of 5 values, all are equal to 1.599999990276e-7.
As soon as I define a min or max value, display is empty.
I made a few tests in case there is a bug in my input or in the code, but result is the same:
- min=0, max=0.00001 or 0.0000002
- min=0.0000000001, max=0.00001
- I exchanged min & max 

 Here is a screenshot if it helps: 

![screenshot](https://owncloud.lal.in2p3.fr/index.php/s/C3LjF8hT6S6XqMA/download)

**Comment by luciozambon** [comment]
from the "export to png" button in the screenshot I deduce that you use Flot and not HighCharts so I need to debug a different part of the program

**Comment by PhilLAL** [comment]
Oh yes, I forgot to give this precision, sorry

**Comment by luciozambon** [comment]
It looks like a bug of Flot js
I've tried a newer version without success
The only idea I've right now is to inhibit to check at the same time Flot, max min and log; you must leave out one of them

**Comment by PhilLAL** [comment]
Thank you for your investigation.
I would say we cannot use log with at least one definition of max/min. 

Did you already wrote a bug report to `flot.js` ?

**Comment by PhilLAL** [comment]
Hi @luciozambon 
just a reminder to check if a bug report has been sent to `flot.js`

**Comment by PhilLAL** [comment]
I tried 1.16.3 version but without success for log scale display.
My config  is probably wrong, here it is:

- [x] Logarithmic
- Decimation `maxmin`  number of samples `1000` (default) 
- Select output 
[x] Chart.js [ ] Flot

**Comment by luciozambon** [comment]
In my setup it works, have you tried to expand the range using max and min?

[image: egiga_chartjs_logY.png]

**Comment by PhilLAL** [comment]
I do not see the image, but here is my config and result:
![config](https://owncloud.lal.in2p3.fr/index.php/s/SsWvWOOphdlHs46/download)
![display](https://owncloud.lal.in2p3.fr/index.php/s/KSk4EpXqGMq84eU/download)

**Comment by luciozambon** [comment]
In your chart equal intervals on Y axes are not equally spaced because it
is a logarithmic scale
It doesn't look like a logarithmic scale because you have a limited range,
less than 2 decades. It should be much more evident with signals ranging 4
or more decades (i.e. the bigger point should be more than 10000 times the
smaller one)

**Comment by PhilLAL** [comment]
Indeed, it seems to work.
Thank you
